### ISSUE TITLE
buginthecode

### ISSUE THREAD

**Issue by akulasathish** [akulasathish/wipro#1]
i see bug in the code please correct it.

**Comment by bipeensinha** [comment]
Hi Satish I am working 
![AzureSeubscriptionSecurity2](https://user-images.githubusercontent.com/49720823/97133398-f9853f00-176f-11eb-87c4-f797a83cfb2d.JPG)
on will poist the upadtye

**Comment by akulasathish** [comment]
thankyou

**Comment by bipeensinha** [comment]
Thanks Lets close this issues as it resolve

**Comment by akulasathish** [comment]
ok guys im closing the issues.
